import type { CustomerAccount, SavedReply } from "@/lib/types";

export const customerAccounts: CustomerAccount[] = [
  {
    id: "account_ashpazi_charcoal_kitchen",
    name: "Ashpazi - Charcoal Kitchen",
    accountType: "pilot",
    plan: "Pilot",
    billingStatus: "exempt",
    active: true,
    locations: [
      {
        id: "ashpazi_charcoal_kitchen_batley",
        businessName: "Ashpazi - Charcoal Kitchen",
        businessType: "Takeaway / Restaurant",
        location: "Batley",
        address: "241 Bradford Rd, Batley WF17 6JQ",
        phone: "01924 929939",
        website: "ashpazi.co.uk",
        googleRating: 4.6,
        googleReviewCount: 167,
        priceRange: "£10-20",
        status: "Google Business Profile integration coming soon",
        plan: "Pilot",
        billingStatus: "exempt",
        pilotStatus: "active",
        accountType: "pilot",
        active: true,
        gbpConnectionStatus: "Google Business Profile integration coming soon",
        brandVoice: {
          businessName: "Ashpazi - Charcoal Kitchen",
          businessType: "Takeaway / Restaurant",
          location: "Batley",
          preferredTone: "Friendly",
          defaultLength: "Standard",
          greetingStyle: "Use warm, appreciative wording",
          signOffStyle: "Thanks, the Ashpazi team",
          wordsToUse: "food, flavour, charcoal grill, collection, friendly",
          wordsToAvoid: "fault, blame, guaranteed",
          complaintHandlingStyle:
            "Apologise for the experience, avoid arguing, and invite the customer to contact the restaurant directly.",
          useEmojis: false,
          mentionBusinessName: true,
          apologiseForPoorExperiences: true,
          inviteUnhappyCustomersToContact: true,
          keepRepliesShortByDefault: false,
        },
      },
    ],
    reviews: [
      {
        id: "rev_ashpazi_amina",
        customerName: "Amina K",
        rating: 5,
        reviewText:
          "Food was fresh, full of flavour and ready on time for collection. The mixed grill was excellent.",
        source: "Google",
        businessName: "Ashpazi - Charcoal Kitchen",
        businessType: "Takeaway / Restaurant",
        location: "Batley",
        address: "241 Bradford Rd, Batley WF17 6JQ",
        phone: "01924 929939",
        website: "ashpazi.co.uk",
        googleRating: 4.6,
        googleReviewCount: 167,
        priceRange: "£10-20",
        dateReceived: "2026-06-09",
        status: "draft_ready",
        sentiment: "Positive",
        draftReplies: [
          "Thank you Amina, we really appreciate your kind words. We are pleased you enjoyed the fresh food, flavour, and mixed grill. Thanks, the Ashpazi team.",
          "Hi Amina, thank you for taking the time to leave such a lovely review. It is great to hear your collection was ready on time and that you enjoyed the mixed grill.",
          "Thank you Amina. We are delighted the food was fresh and full of flavour for you, and we hope to welcome you again soon.",
        ],
      },
      {
        id: "rev_ashpazi_daniel",
        customerName: "Daniel R",
        rating: 4,
        reviewText:
          "Really tasty food and friendly staff. Collection was a little busy but overall very good.",
        source: "Google",
        businessName: "Ashpazi - Charcoal Kitchen",
        businessType: "Takeaway / Restaurant",
        location: "Batley",
        address: "241 Bradford Rd, Batley WF17 6JQ",
        phone: "01924 929939",
        website: "ashpazi.co.uk",
        googleRating: 4.6,
        googleReviewCount: 167,
        priceRange: "£10-20",
        dateReceived: "2026-06-08",
        status: "draft_ready",
        sentiment: "Positive",
        draftReplies: [
          "Thank you Daniel, we are glad you enjoyed the food and found the team friendly. We appreciate your patience during a busy collection time. Thanks, the Ashpazi team.",
          "Hi Daniel, thanks for your helpful review. It is lovely to hear the food was tasty, and we will keep working to make busy collection times smoother.",
          "Thank you Daniel. We really appreciate your feedback and are pleased your overall experience was very good.",
        ],
      },
      {
        id: "rev_ashpazi_sam",
        customerName: "Sam P",
        rating: 1,
        reviewText:
          "Delivery took much longer than expected and one item was missing from the order.",
        source: "Google",
        businessName: "Ashpazi - Charcoal Kitchen",
        businessType: "Takeaway / Restaurant",
        location: "Batley",
        address: "241 Bradford Rd, Batley WF17 6JQ",
        phone: "01924 929939",
        website: "ashpazi.co.uk",
        googleRating: 4.6,
        googleReviewCount: 167,
        priceRange: "£10-20",
        dateReceived: "2026-06-07",
        status: "new",
        sentiment: "Complaint",
        draftReplies: [
          "Hi Sam, we are sorry your delivery took longer than expected and that an item was missing. Please contact the restaurant directly with your order details so we can look into this properly. Thanks, the Ashpazi team.",
          "Thank you for letting us know, Sam. We apologise for the delay and missing item, and we would like the chance to review what happened with your order.",
          "Hi Sam, this is not the experience we want for our customers. Please get in touch with the restaurant directly so the team can help.",
        ],
      },
    ],
    savedReplies: [],
  },
  {
    id: "account_gardner_champion_solicitors",
    name: "Gardner Champion Solicitors Ltd",
    accountType: "pilot",
    plan: "Pilot",
    billingStatus: "exempt",
    active: true,
    locations: [
      {
        id: "gardner_champion_dewsbury",
        businessName: "Gardner Champion Solicitors Ltd",
        businessType: "Legal services / Solicitors",
        location: "Dewsbury",
        address: "Business Centre, 13 Wellington Rd, Dewsbury WF13 1HL",
        phone: "0333 034 4629",
        googleRating: 5.0,
        googleReviewCount: 23,
        status: "Google Business Profile integration coming soon",
        plan: "Pilot",
        billingStatus: "exempt",
        pilotStatus: "active",
        accountType: "pilot",
        active: true,
        gbpConnectionStatus: "Google Business Profile integration coming soon",
        brandVoice: {
          businessName: "Gardner Champion Solicitors Ltd",
          businessType: "Legal services / Solicitors",
          location: "Dewsbury",
          preferredTone: "Professional",
          defaultLength: "Standard",
          greetingStyle: "Use a polite, reassuring greeting",
          signOffStyle: "Kind regards, Gardner Champion Solicitors",
          wordsToUse: "professional, helpful, clear, supported, efficient",
          wordsToAvoid: "fault, blame, liability, guaranteed, case details",
          complaintHandlingStyle:
            "Acknowledge feedback carefully, avoid discussing case details publicly, avoid admitting liability, and invite the client to contact the firm directly.",
          useEmojis: false,
          mentionBusinessName: true,
          apologiseForPoorExperiences: true,
          inviteUnhappyCustomersToContact: true,
          keepRepliesShortByDefault: false,
        },
      },
      {
        id: "gardner_champion_rugeley",
        businessName: "Gardner Champion Solicitors Ltd",
        businessType: "Law firm / Solicitors",
        location: "Rugeley",
        address: "Brook House, Brook Sq, Rugeley WS15 2DT",
        phone: "0333 034 4629",
        googleRating: 4.4,
        googleReviewCount: 57,
        status: "Google Business Profile integration coming soon",
        plan: "Pilot",
        billingStatus: "exempt",
        pilotStatus: "active",
        accountType: "pilot",
        active: true,
        gbpConnectionStatus: "Google Business Profile integration coming soon",
        brandVoice: {
          businessName: "Gardner Champion Solicitors Ltd",
          businessType: "Law firm / Solicitors",
          location: "Rugeley",
          preferredTone: "Professional",
          defaultLength: "Standard",
          greetingStyle: "Use a calm, reassuring greeting",
          signOffStyle: "Kind regards, Gardner Champion Solicitors",
          wordsToUse: "professional, support, advice, communication, helpful",
          wordsToAvoid: "fault, blame, liability, guaranteed, case details",
          complaintHandlingStyle:
            "For lower-star reviews, avoid defensive wording, avoid discussing case details publicly, and invite the reviewer to contact the firm directly.",
          useEmojis: false,
          mentionBusinessName: true,
          apologiseForPoorExperiences: true,
          inviteUnhappyCustomersToContact: true,
          keepRepliesShortByDefault: false,
        },
      },
    ],
    reviews: [
      {
        id: "rev_gardner_dewsbury_farah",
        customerName: "Farah M",
        rating: 5,
        reviewText:
          "Very professional and helpful throughout. Everything was explained clearly and I felt well supported.",
        source: "Google",
        businessName: "Gardner Champion Solicitors Ltd",
        businessType: "Legal services / Solicitors",
        location: "Dewsbury",
        address: "Business Centre, 13 Wellington Rd, Dewsbury WF13 1HL",
        phone: "0333 034 4629",
        googleRating: 5.0,
        googleReviewCount: 23,
        dateReceived: "2026-06-09",
        status: "draft_ready",
        sentiment: "Positive",
        draftReplies: [
          "Dear Farah, thank you for your kind review. We are pleased you felt supported and that everything was explained clearly. Kind regards, Gardner Champion Solicitors.",
          "Thank you Farah. We appreciate your feedback and are glad the service felt professional, helpful, and clear throughout.",
          "Dear Farah, thank you for taking the time to share your experience. We are pleased the team were able to support you well.",
        ],
      },
      {
        id: "rev_gardner_dewsbury_david",
        customerName: "David H",
        rating: 5,
        reviewText:
          "Excellent service from start to finish. Communication was clear and the matter was handled efficiently.",
        source: "Google",
        businessName: "Gardner Champion Solicitors Ltd",
        businessType: "Legal services / Solicitors",
        location: "Dewsbury",
        address: "Business Centre, 13 Wellington Rd, Dewsbury WF13 1HL",
        phone: "0333 034 4629",
        googleRating: 5.0,
        googleReviewCount: 23,
        dateReceived: "2026-06-08",
        status: "draft_ready",
        sentiment: "Positive",
        draftReplies: [
          "Dear David, thank you for your kind feedback. We are pleased the communication was clear and your matter was handled efficiently. Kind regards, Gardner Champion Solicitors.",
          "Thank you David. We appreciate your review and are glad you received excellent service from start to finish.",
          "Dear David, thank you for taking the time to leave a review. Clear communication and efficient service are very important to us.",
        ],
      },
      {
        id: "rev_gardner_dewsbury_rachel",
        customerName: "Rachel T",
        rating: 2,
        reviewText:
          "I found it difficult to get updates and had to chase a few times. The advice was good but communication could have been better.",
        source: "Google",
        businessName: "Gardner Champion Solicitors Ltd",
        businessType: "Legal services / Solicitors",
        location: "Dewsbury",
        address: "Business Centre, 13 Wellington Rd, Dewsbury WF13 1HL",
        phone: "0333 034 4629",
        googleRating: 5.0,
        googleReviewCount: 23,
        dateReceived: "2026-06-07",
        status: "new",
        sentiment: "Complaint",
        draftReplies: [
          "Dear Rachel, thank you for your feedback. We are sorry to hear communication did not meet your expectations, although we are pleased the advice was helpful. To avoid discussing details publicly, please contact the firm directly so this can be reviewed appropriately. Kind regards, Gardner Champion Solicitors.",
          "Dear Rachel, we appreciate you sharing your experience. Clear communication matters, and we would welcome the opportunity to understand your concerns directly.",
          "Thank you Rachel. We are sorry to hear you had difficulty receiving updates. Please contact the office directly so the matter can be looked into carefully.",
        ],
      },
      {
        id: "rev_gardner_rugeley_michael",
        customerName: "Michael B",
        rating: 5,
        reviewText:
          "Friendly, professional and very knowledgeable. I would happily recommend Gardner Champion to others.",
        source: "Google",
        businessName: "Gardner Champion Solicitors Ltd",
        businessType: "Law firm / Solicitors",
        location: "Rugeley",
        address: "Brook House, Brook Sq, Rugeley WS15 2DT",
        phone: "0333 034 4629",
        googleRating: 4.4,
        googleReviewCount: 57,
        dateReceived: "2026-06-09",
        status: "draft_ready",
        sentiment: "Positive",
        draftReplies: [
          "Dear Michael, thank you for your kind review and recommendation. We are pleased you found the team friendly, professional, and knowledgeable. Kind regards, Gardner Champion Solicitors.",
          "Thank you Michael. We appreciate your feedback and are glad the Rugeley team were able to support you professionally.",
          "Dear Michael, thank you for taking the time to recommend Gardner Champion. Your feedback is much appreciated.",
        ],
      },
      {
        id: "rev_gardner_rugeley_anita",
        customerName: "Anita S",
        rating: 4,
        reviewText:
          "Good service and helpful advice. There was a small delay at one point but overall I was pleased.",
        source: "Google",
        businessName: "Gardner Champion Solicitors Ltd",
        businessType: "Law firm / Solicitors",
        location: "Rugeley",
        address: "Brook House, Brook Sq, Rugeley WS15 2DT",
        phone: "0333 034 4629",
        googleRating: 4.4,
        googleReviewCount: 57,
        dateReceived: "2026-06-08",
        status: "draft_ready",
        sentiment: "Positive",
        draftReplies: [
          "Dear Anita, thank you for your feedback. We are pleased you were happy overall and found the advice helpful. We also appreciate your patience regarding the delay. Kind regards, Gardner Champion Solicitors.",
          "Thank you Anita. We appreciate your balanced review and are glad the service and advice were helpful.",
          "Dear Anita, thank you for taking the time to share your experience. We are pleased the overall service met your expectations.",
        ],
      },
      {
        id: "rev_gardner_rugeley_lee",
        customerName: "Lee W",
        rating: 1,
        reviewText:
          "I was disappointed with the lack of communication and felt the process took longer than expected.",
        source: "Google",
        businessName: "Gardner Champion Solicitors Ltd",
        businessType: "Law firm / Solicitors",
        location: "Rugeley",
        address: "Brook House, Brook Sq, Rugeley WS15 2DT",
        phone: "0333 034 4629",
        googleRating: 4.4,
        googleReviewCount: 57,
        dateReceived: "2026-06-07",
        status: "new",
        sentiment: "Complaint",
        draftReplies: [
          "Dear Lee, thank you for your feedback. We are sorry to hear communication and timescales did not meet your expectations. To avoid discussing details publicly, please contact the firm directly so your concerns can be reviewed appropriately. Kind regards, Gardner Champion Solicitors.",
          "Dear Lee, we appreciate you raising this. Clear communication is important, and we would welcome the chance to understand your experience directly.",
          "Thank you Lee. We are sorry to hear you were disappointed. Please contact the office directly so this can be looked into carefully.",
        ],
      },
    ],
    savedReplies: [],
  },
  {
    id: "account_masjid_as_salaam",
    name: "Masjid As-Salaam",
    accountType: "pilot",
    plan: "Free for Life",
    billingStatus: "exempt",
    active: true,
    locations: [
      {
        id: "masjid_as_salaam_earlsheaton",
        businessName: "Masjid As-Salaam",
        businessType: "Mosque / community organisation",
        location: "Masjid As-Salaam, Earlsheaton",
        address: "4 New St, Earlsheaton, Dewsbury WF12 8JJ",
        phone: "07424 239866",
        googleRating: 4.9,
        googleReviewCount: 43,
        status: "Google Business Profile integration coming soon",
        plan: "Free for Life",
        billingStatus: "exempt",
        pilotStatus: "active",
        accountType: "pilot",
        active: true,
        gbpConnectionStatus: "Google Business Profile integration coming soon",
        brandVoice: {
          businessName: "Masjid As-Salaam",
          businessType: "Mosque / community organisation",
          location: "Masjid As-Salaam, Earlsheaton",
          preferredTone: "Friendly",
          defaultLength: "Standard",
          greetingStyle: "Use a respectful, warm greeting",
          signOffStyle: "With thanks, Masjid As-Salaam",
          wordsToUse: "community, welcoming, peaceful, helpful, respectful",
          wordsToAvoid: "corporate, transaction, customer, guaranteed",
          complaintHandlingStyle:
            "Acknowledge concerns with care, avoid defensive wording, and invite the reviewer to contact the masjid directly so the matter can be understood properly.",
          useEmojis: false,
          mentionBusinessName: true,
          apologiseForPoorExperiences: true,
          inviteUnhappyCustomersToContact: true,
          keepRepliesShortByDefault: false,
        },
      },
    ],
    reviews: [
      {
        id: "rev_masjid_as_salaam_yusuf",
        customerName: "Yusuf A",
        rating: 5,
        reviewText:
          "A peaceful and welcoming masjid with a strong sense of community. The facilities are clean and the volunteers are always helpful.",
        source: "Google",
        businessName: "Masjid As-Salaam",
        businessType: "Mosque / community organisation",
        location: "Masjid As-Salaam, Earlsheaton",
        address: "4 New St, Earlsheaton, Dewsbury WF12 8JJ",
        phone: "07424 239866",
        googleRating: 4.9,
        googleReviewCount: 43,
        dateReceived: "2026-06-09",
        status: "draft_ready",
        sentiment: "Positive",
        draftReplies: [
          "Thank you Yusuf, we really appreciate your kind words. It is lovely to hear that you found the masjid peaceful, welcoming, and well cared for. With thanks, Masjid As-Salaam.",
          "Dear Yusuf, thank you for taking the time to leave such thoughtful feedback. We are grateful to hear that the community and volunteers made you feel welcome.",
          "Thank you Yusuf. We are pleased the facilities and volunteer support have been helpful, and we appreciate your duas and support for the masjid.",
        ],
      },
      {
        id: "rev_masjid_as_salaam_amina",
        customerName: "Amina H",
        rating: 4,
        reviewText:
          "A very welcoming place for families. It would be helpful to have clearer updates online about class times and community events.",
        source: "Google",
        businessName: "Masjid As-Salaam",
        businessType: "Mosque / community organisation",
        location: "Masjid As-Salaam, Earlsheaton",
        address: "4 New St, Earlsheaton, Dewsbury WF12 8JJ",
        phone: "07424 239866",
        googleRating: 4.9,
        googleReviewCount: 43,
        dateReceived: "2026-06-08",
        status: "draft_ready",
        sentiment: "Positive",
        draftReplies: [
          "Thank you Amina, we appreciate your kind and helpful feedback. We are glad families feel welcome, and we will keep working on clearer updates for classes and community events. With thanks, Masjid As-Salaam.",
          "Dear Amina, thank you for sharing this. It is lovely to hear the masjid feels welcoming for families, and your point about clearer online updates is very helpful.",
          "Thank you Amina. We are grateful for your feedback and will take your suggestion about class and event updates on board.",
        ],
      },
      {
        id: "rev_masjid_as_salaam_hassan",
        customerName: "Hassan R",
        rating: 1,
        reviewText:
          "I came for an event but could not find clear information about parking or timings. I felt quite disappointed and unsure who to ask.",
        source: "Google",
        businessName: "Masjid As-Salaam",
        businessType: "Mosque / community organisation",
        location: "Masjid As-Salaam, Earlsheaton",
        address: "4 New St, Earlsheaton, Dewsbury WF12 8JJ",
        phone: "07424 239866",
        googleRating: 4.9,
        googleReviewCount: 43,
        dateReceived: "2026-06-07",
        status: "new",
        sentiment: "Complaint",
        draftReplies: [
          "Dear Hassan, thank you for letting us know. We are sorry the parking and timing information was not clear and that this affected your visit. Please contact the masjid directly so we can understand what happened and improve this for future events. With thanks, Masjid As-Salaam.",
          "Thank you Hassan, we are sorry to hear you felt unsure on the day. Clear information matters, especially for community events, and we would welcome the chance to speak with you directly.",
          "Dear Hassan, we appreciate your feedback and are sorry your visit was disappointing. Please get in touch with the masjid so the team can look into the details properly.",
        ],
      },
    ],
    savedReplies: [],
  },
];

export const customerLocations = customerAccounts.flatMap(
  (account) => account.locations,
);

export const customerReviews = customerAccounts.flatMap(
  (account) => account.reviews,
);

export const customerSavedReplies: SavedReply[] = customerAccounts.flatMap(
  (account) =>
    account.reviews
      .filter((review) => review.status !== "new")
      .map((review, index) => ({
        id: `saved_${review.id}`,
        reviewId: review.id,
        originalReviewSnippet: review.reviewText,
        replyPreview: review.draftReplies[0],
        tone: review.sentiment === "Complaint" ? "Empathetic" : "Friendly",
        businessType: review.businessType,
        dateSaved: `2026-06-0${9 - index}`,
        usageCount: [2, 1][index] ?? 1,
        sentiment: review.sentiment,
      })),
);
