import type {
  BrandVoiceSettings,
  GoogleBusinessLocation,
  Review,
  SavedReply,
} from "@/lib/types";

export type PilotLocation = GoogleBusinessLocation & {
  businessType: Review["businessType"];
  brandVoice: BrandVoiceSettings;
};

export const pilotLocations: PilotLocation[] = [
  {
    id: "ashpazi_batley",
    businessName: "Ashpazi - Charcoal Kitchen",
    businessType: "Takeaway / Restaurant",
    location: "Batley",
    address: "241 Bradford Rd, Batley WF17 6JQ",
    phone: "01924 929939",
    website: "ashpazi.co.uk",
    googleRating: 4.6,
    googleReviewCount: 167,
    priceRange: "£10-20",
    status: "Connected",
    brandVoice: {
      businessName: "Ashpazi - Charcoal Kitchen",
      businessType: "Takeaway / Restaurant",
      location: "Batley",
      preferredTone: "Friendly",
      defaultLength: "Standard",
      greetingStyle: "Use the customer's first name where appropriate",
      signOffStyle: "Thanks, the Ashpazi team",
      wordsToUse: "fresh, flavour, charcoal grill, friendly, collection, order",
      wordsToAvoid: "fault, blame, guaranteed",
      complaintHandlingStyle:
        "Apologise for the experience, avoid arguing, and invite the customer to contact the restaurant directly.",
      useEmojis: false,
      mentionBusinessName: true,
      apologiseForPoorExperiences: true,
      inviteUnhappyCustomersToContact: true,
      keepRepliesShortByDefault: false,
    },
  },
  {
    id: "gardner_dewsbury",
    businessName: "Gardner Champion Solicitors Ltd",
    businessType: "Legal services / Solicitors",
    location: "Dewsbury",
    address: "Business Centre, 13 Wellington Rd, Dewsbury WF13 1HL",
    phone: "0333 034 4629",
    googleRating: 5.0,
    googleReviewCount: 23,
    status: "Connected",
    brandVoice: {
      businessName: "Gardner Champion Solicitors Ltd",
      businessType: "Legal services / Solicitors",
      location: "Dewsbury",
      preferredTone: "Professional",
      defaultLength: "Standard",
      greetingStyle: "Use a polite greeting and avoid informal phrasing",
      signOffStyle: "Kind regards, Gardner Champion Solicitors",
      wordsToUse: "professional, clear, supportive, efficient, reassuring",
      wordsToAvoid: "case details, fault, liability, guaranteed outcome",
      complaintHandlingStyle:
        "Acknowledge feedback carefully, avoid discussing case details publicly, and invite the client to contact the firm directly.",
      useEmojis: false,
      mentionBusinessName: true,
      apologiseForPoorExperiences: false,
      inviteUnhappyCustomersToContact: true,
      keepRepliesShortByDefault: false,
    },
  },
  {
    id: "gardner_rugeley",
    businessName: "Gardner Champion Solicitors Ltd",
    businessType: "Law firm / Solicitors",
    location: "Rugeley",
    address: "Brook House, Brook Sq, Rugeley WS15 2DT",
    phone: "0333 034 4629",
    googleRating: 4.4,
    googleReviewCount: 57,
    status: "Connected",
    brandVoice: {
      businessName: "Gardner Champion Solicitors Ltd",
      businessType: "Law firm / Solicitors",
      location: "Rugeley",
      preferredTone: "Professional",
      defaultLength: "Standard",
      greetingStyle: "Use a calm, professional greeting",
      signOffStyle: "Kind regards, Gardner Champion Solicitors",
      wordsToUse: "professional, calm, reassuring, discreet, helpful",
      wordsToAvoid: "case details, fault, blame, liability",
      complaintHandlingStyle:
        "For lower-star reviews, avoid defensive wording and invite the reviewer to contact the firm directly.",
      useEmojis: false,
      mentionBusinessName: true,
      apologiseForPoorExperiences: false,
      inviteUnhappyCustomersToContact: true,
      keepRepliesShortByDefault: false,
    },
  },
];

export const defaultBrandVoice: BrandVoiceSettings =
  pilotLocations[0].brandVoice;

export const mockLocations: GoogleBusinessLocation[] = pilotLocations.map(
  ({
    id,
    businessName,
    location,
    address,
    phone,
    website,
    googleRating,
    googleReviewCount,
    priceRange,
    status,
  }) => ({
    id,
    businessName,
    location,
    address,
    phone,
    website,
    googleRating,
    googleReviewCount,
    priceRange,
    status,
  }),
);

export const demoReviews: Review[] = [
  {
    id: "rev_ashpazi_amina",
    customerName: "Amina K",
    rating: 5,
    reviewText:
      "Food was fresh, full of flavour and ready on time for collection. The mixed grill was excellent.",
    source: "Google",
    businessName: "Ashpazi - Charcoal Kitchen",
    businessType: "Takeaway / Restaurant",
    location: "Batley",
    address: "241 Bradford Rd, Batley WF17 6JQ",
    phone: "01924 929939",
    website: "ashpazi.co.uk",
    googleRating: 4.6,
    googleReviewCount: 167,
    priceRange: "£10-20",
    dateReceived: "2026-06-09",
    status: "Draft ready",
    sentiment: "Positive",
    draftReplies: [
      "Hi Amina, thank you for your lovely review. We are so pleased the food was fresh, full of flavour and ready on time for collection. It is great to hear you enjoyed the mixed grill. Thanks, the Ashpazi team.",
      "Thank you, Amina. We really appreciate your kind words about the mixed grill and collection experience. The Ashpazi team will be delighted to hear this.",
      "Hi Amina, thanks for taking the time to review us. We are glad you enjoyed the fresh flavours and charcoal grill, and we hope to welcome you back soon. Thanks, the Ashpazi team.",
    ],
  },
  {
    id: "rev_ashpazi_daniel",
    customerName: "Daniel R",
    rating: 4,
    reviewText:
      "Really tasty food and friendly staff. Collection was a little busy but overall very good.",
    source: "Google",
    businessName: "Ashpazi - Charcoal Kitchen",
    businessType: "Takeaway / Restaurant",
    location: "Batley",
    address: "241 Bradford Rd, Batley WF17 6JQ",
    phone: "01924 929939",
    website: "ashpazi.co.uk",
    googleRating: 4.6,
    googleReviewCount: 167,
    priceRange: "£10-20",
    dateReceived: "2026-06-08",
    status: "Draft ready",
    sentiment: "Positive",
    draftReplies: [
      "Hi Daniel, thank you for your kind review. We are pleased you enjoyed the food and friendly service. We appreciate your patience while collection was busy and hope to see you again soon. Thanks, the Ashpazi team.",
      "Thank you, Daniel. It is great to hear the food and staff made a good impression. We will keep working on making busy collection times smoother.",
      "Hi Daniel, thanks for visiting Ashpazi in Batley. We are glad you enjoyed the food overall and appreciate your helpful feedback about collection.",
    ],
  },
  {
    id: "rev_ashpazi_sam",
    customerName: "Sam P",
    rating: 1,
    reviewText:
      "Delivery took much longer than expected and one item was missing from the order.",
    source: "Google",
    businessName: "Ashpazi - Charcoal Kitchen",
    businessType: "Takeaway / Restaurant",
    location: "Batley",
    address: "241 Bradford Rd, Batley WF17 6JQ",
    phone: "01924 929939",
    website: "ashpazi.co.uk",
    googleRating: 4.6,
    googleReviewCount: 167,
    priceRange: "£10-20",
    dateReceived: "2026-06-07",
    status: "New",
    sentiment: "Complaint",
    draftReplies: [
      "Hi Sam, thank you for letting us know. We are sorry your delivery took longer than expected and that an item was missing. Please contact the restaurant directly with your order details so we can look into this for you. Thanks, the Ashpazi team.",
      "Hello Sam, we are sorry to hear about your delivery experience. A long wait and missing item is frustrating, and we would like to review the order. Please get in touch with Ashpazi directly so the team can help.",
      "Hi Sam, thank you for your feedback. We apologise that your order did not arrive as expected. Please contact the restaurant with the order information and we will look into it carefully.",
    ],
  },
  {
    id: "rev_gardner_dewsbury_farah",
    customerName: "Farah M",
    rating: 5,
    reviewText:
      "Very professional and helpful throughout. Everything was explained clearly and I felt well supported.",
    source: "Google",
    businessName: "Gardner Champion Solicitors Ltd",
    businessType: "Legal services / Solicitors",
    location: "Dewsbury",
    address: "Business Centre, 13 Wellington Rd, Dewsbury WF13 1HL",
    phone: "0333 034 4629",
    googleRating: 5.0,
    googleReviewCount: 23,
    dateReceived: "2026-06-06",
    status: "Draft ready",
    sentiment: "Positive",
    draftReplies: [
      "Dear Farah, thank you for your kind review. We are pleased to hear that the advice was explained clearly and that you felt well supported throughout. Kind regards, Gardner Champion Solicitors.",
      "Thank you, Farah. We are grateful for your feedback and are glad our team provided professional, helpful support. Kind regards, Gardner Champion Solicitors.",
      "Dear Farah, thank you for taking the time to share your experience. Clear communication and supportive service are very important to us. Kind regards, Gardner Champion Solicitors.",
    ],
  },
  {
    id: "rev_gardner_dewsbury_david",
    customerName: "David H",
    rating: 5,
    reviewText:
      "Excellent service from start to finish. Communication was clear and the matter was handled efficiently.",
    source: "Google",
    businessName: "Gardner Champion Solicitors Ltd",
    businessType: "Legal services / Solicitors",
    location: "Dewsbury",
    address: "Business Centre, 13 Wellington Rd, Dewsbury WF13 1HL",
    phone: "0333 034 4629",
    googleRating: 5.0,
    googleReviewCount: 23,
    dateReceived: "2026-06-05",
    status: "Posted",
    sentiment: "Positive",
    draftReplies: [
      "Dear David, thank you for your review. We are pleased to hear that communication was clear and that your matter was handled efficiently. Kind regards, Gardner Champion Solicitors.",
      "Thank you, David. We appreciate your feedback and are glad you received excellent service from start to finish. Kind regards, Gardner Champion Solicitors.",
      "Dear David, thank you for taking the time to leave a review. We are pleased the team provided clear communication and efficient support. Kind regards, Gardner Champion Solicitors.",
    ],
  },
  {
    id: "rev_gardner_dewsbury_rachel",
    customerName: "Rachel T",
    rating: 2,
    reviewText:
      "I found it difficult to get updates and had to chase a few times. The advice was good but communication could have been better.",
    source: "Google",
    businessName: "Gardner Champion Solicitors Ltd",
    businessType: "Legal services / Solicitors",
    location: "Dewsbury",
    address: "Business Centre, 13 Wellington Rd, Dewsbury WF13 1HL",
    phone: "0333 034 4629",
    googleRating: 5.0,
    googleReviewCount: 23,
    dateReceived: "2026-06-04",
    status: "Edited",
    sentiment: "Complaint",
    draftReplies: [
      "Dear Rachel, thank you for your feedback. We are sorry to hear that communication did not meet your expectations, although we are pleased the advice was helpful. Please contact the Dewsbury office directly so we can review your concerns appropriately. Kind regards, Gardner Champion Solicitors.",
      "Dear Rachel, we appreciate you taking the time to share this. We understand that timely updates are important and we are sorry you felt you had to chase. Please contact the firm directly so this can be looked into with care. Kind regards, Gardner Champion Solicitors.",
      "Thank you, Rachel. We value your feedback and will consider your comments about communication carefully. To avoid discussing details publicly, please contact our office directly if you would like to speak further. Kind regards, Gardner Champion Solicitors.",
    ],
  },
  {
    id: "rev_gardner_rugeley_michael",
    customerName: "Michael B",
    rating: 5,
    reviewText:
      "Friendly, professional and very knowledgeable. I would happily recommend Gardner Champion to others.",
    source: "Google",
    businessName: "Gardner Champion Solicitors Ltd",
    businessType: "Law firm / Solicitors",
    location: "Rugeley",
    address: "Brook House, Brook Sq, Rugeley WS15 2DT",
    phone: "0333 034 4629",
    googleRating: 4.4,
    googleReviewCount: 57,
    dateReceived: "2026-06-03",
    status: "Draft ready",
    sentiment: "Positive",
    draftReplies: [
      "Dear Michael, thank you for your kind recommendation. We are pleased to hear that you found the team friendly, professional and knowledgeable. Kind regards, Gardner Champion Solicitors.",
      "Thank you, Michael. We are grateful for your feedback and pleased that our Rugeley team provided professional support. Kind regards, Gardner Champion Solicitors.",
      "Dear Michael, thank you for taking the time to review Gardner Champion. Your recommendation is very much appreciated. Kind regards, Gardner Champion Solicitors.",
    ],
  },
  {
    id: "rev_gardner_rugeley_anita",
    customerName: "Anita S",
    rating: 4,
    reviewText:
      "Good service and helpful advice. There was a small delay at one point but overall I was pleased.",
    source: "Google",
    businessName: "Gardner Champion Solicitors Ltd",
    businessType: "Law firm / Solicitors",
    location: "Rugeley",
    address: "Brook House, Brook Sq, Rugeley WS15 2DT",
    phone: "0333 034 4629",
    googleRating: 4.4,
    googleReviewCount: 57,
    dateReceived: "2026-06-02",
    status: "Copied",
    sentiment: "Positive",
    draftReplies: [
      "Dear Anita, thank you for your feedback. We are pleased you found the service good and the advice helpful, and we appreciate your patience regarding the delay. Kind regards, Gardner Champion Solicitors.",
      "Thank you, Anita. We are glad you were pleased overall and appreciate your balanced comments about the service and advice. Kind regards, Gardner Champion Solicitors.",
      "Dear Anita, thank you for taking the time to leave a review. Your feedback about the helpful advice and the delay is appreciated. Kind regards, Gardner Champion Solicitors.",
    ],
  },
  {
    id: "rev_gardner_rugeley_lee",
    customerName: "Lee W",
    rating: 1,
    reviewText:
      "I was disappointed with the lack of communication and felt the process took longer than expected.",
    source: "Google",
    businessName: "Gardner Champion Solicitors Ltd",
    businessType: "Law firm / Solicitors",
    location: "Rugeley",
    address: "Brook House, Brook Sq, Rugeley WS15 2DT",
    phone: "0333 034 4629",
    googleRating: 4.4,
    googleReviewCount: 57,
    dateReceived: "2026-06-01",
    status: "New",
    sentiment: "Complaint",
    draftReplies: [
      "Dear Lee, thank you for your feedback. We are sorry to hear that communication and timescales did not meet your expectations. To avoid discussing details publicly, please contact the Rugeley office directly so your concerns can be reviewed appropriately. Kind regards, Gardner Champion Solicitors.",
      "Dear Lee, we appreciate you taking the time to share your experience. We understand that clear communication is important, and we would welcome the opportunity to look into your concerns directly. Kind regards, Gardner Champion Solicitors.",
      "Thank you, Lee. We are disappointed to hear about your experience and will treat your comments carefully. Please contact the firm directly so this can be discussed in the appropriate setting. Kind regards, Gardner Champion Solicitors.",
    ],
  },
];

export const savedReplies: SavedReply[] = demoReviews
  .filter((review) => review.status !== "New")
  .slice(0, 5)
  .map((review, index) => ({
    id: `saved_${review.id}`,
    reviewId: review.id,
    originalReviewSnippet: review.reviewText,
    replyPreview: review.draftReplies[0],
    tone: review.businessName.includes("Gardner")
      ? "Professional"
      : review.sentiment === "Complaint"
        ? "Empathetic"
        : "Friendly",
    businessType: review.businessType,
    dateSaved: `2026-06-0${9 - index}`,
    usageCount: [8, 6, 4, 7, 3][index],
    sentiment: review.sentiment,
  }));
