import type {
  BrandVoiceSettings,
  GoogleBusinessLocation,
  Review,
  SavedReply,
} from "@/lib/types";

// All businesses and reviews used in demo mode are fictional examples for product testing.
export type DemoLocation = GoogleBusinessLocation & {
  businessType: Review["businessType"];
  brandVoice: BrandVoiceSettings;
};

export const demoLocations: DemoLocation[] = [
  {
    id: "example_hair_salon_leeds",
    businessName: "Example Hair Salon",
    businessType: "Salon",
    location: "Leeds",
    address: "Example High Street, Leeds",
    googleRating: 4.8,
    googleReviewCount: 124,
    priceRange: "£20-50",
    status: "Connected",
    brandVoice: {
      businessName: "Example Hair Salon",
      businessType: "Salon",
      location: "Leeds",
      preferredTone: "Friendly",
      defaultLength: "Standard",
      greetingStyle: "Use the customer's first name where appropriate",
      signOffStyle: "Thanks, the Example Hair Salon team",
      wordsToUse: "friendly, professional, welcoming, pleased, result",
      wordsToAvoid: "cheap, fault, blame, guaranteed",
      complaintHandlingStyle:
        "Apologise for the experience, avoid defensive wording, and invite the customer to contact the salon directly.",
      useEmojis: false,
      mentionBusinessName: true,
      apologiseForPoorExperiences: true,
      inviteUnhappyCustomersToContact: true,
      keepRepliesShortByDefault: false,
    },
  },
  {
    id: "example_dental_practice_manchester",
    businessName: "Example Dental Practice",
    businessType: "Dentist",
    location: "Manchester",
    address: "Example Road, Manchester",
    googleRating: 4.5,
    googleReviewCount: 89,
    status: "Connected",
    brandVoice: {
      businessName: "Example Dental Practice",
      businessType: "Dentist",
      location: "Manchester",
      preferredTone: "Empathetic",
      defaultLength: "Standard",
      greetingStyle: "Use a calm, polite greeting",
      signOffStyle: "Kind regards, the Example Dental Practice team",
      wordsToUse: "care, support, clear, helpful, patient",
      wordsToAvoid: "fault, blame, liability, guaranteed",
      complaintHandlingStyle:
        "Acknowledge concerns calmly, avoid discussing treatment details publicly, and invite the patient to contact the practice directly.",
      useEmojis: false,
      mentionBusinessName: true,
      apologiseForPoorExperiences: true,
      inviteUnhappyCustomersToContact: true,
      keepRepliesShortByDefault: false,
    },
  },
  {
    id: "example_local_garage_bradford",
    businessName: "Example Local Garage",
    businessType: "Garage",
    location: "Bradford",
    address: "Example Industrial Estate, Bradford",
    googleRating: 4.7,
    googleReviewCount: 156,
    priceRange: "£50-150",
    status: "Connected",
    brandVoice: {
      businessName: "Example Local Garage",
      businessType: "Garage",
      location: "Bradford",
      preferredTone: "Professional",
      defaultLength: "Short",
      greetingStyle: "Use straightforward, helpful wording",
      signOffStyle: "Thanks, the Example Local Garage team",
      wordsToUse: "clear, fair, reliable, helpful, MOT",
      wordsToAvoid: "cheap, fault, blame, guaranteed",
      complaintHandlingStyle:
        "Acknowledge the issue, avoid arguing, and invite the customer to contact the garage directly.",
      useEmojis: false,
      mentionBusinessName: true,
      apologiseForPoorExperiences: true,
      inviteUnhappyCustomersToContact: true,
      keepRepliesShortByDefault: true,
    },
  },
  {
    id: "example_indian_restaurant_birmingham",
    businessName: "Example Indian Restaurant",
    businessType: "Restaurant",
    location: "Birmingham",
    address: "Example Parade, Birmingham",
    googleRating: 4.4,
    googleReviewCount: 211,
    priceRange: "£10-20",
    status: "Connected",
    brandVoice: {
      businessName: "Example Indian Restaurant",
      businessType: "Restaurant",
      location: "Birmingham",
      preferredTone: "Friendly",
      defaultLength: "Standard",
      greetingStyle: "Use warm, appreciative wording",
      signOffStyle: "Thanks, the Example Indian Restaurant team",
      wordsToUse: "food, flavour, delivery, order, friendly",
      wordsToAvoid: "fault, blame, guaranteed",
      complaintHandlingStyle:
        "Apologise for the experience, avoid arguing, and invite the customer to contact the restaurant directly.",
      useEmojis: false,
      mentionBusinessName: true,
      apologiseForPoorExperiences: true,
      inviteUnhappyCustomersToContact: true,
      keepRepliesShortByDefault: false,
    },
  },
  {
    id: "example_estate_agents_leicester",
    businessName: "Example Estate Agents",
    businessType: "Estate agent",
    location: "Leicester",
    address: "Example Market Street, Leicester",
    googleRating: 4.6,
    googleReviewCount: 73,
    status: "Connected",
    brandVoice: {
      businessName: "Example Estate Agents",
      businessType: "Estate agent",
      location: "Leicester",
      preferredTone: "Professional",
      defaultLength: "Standard",
      greetingStyle: "Use reassuring, professional wording",
      signOffStyle: "Kind regards, the Example Estate Agents team",
      wordsToUse: "updated, process, sale, helpful, clear",
      wordsToAvoid: "guaranteed, fault, blame",
      complaintHandlingStyle:
        "Acknowledge feedback, avoid defensive wording, and invite the client to contact the office directly.",
      useEmojis: false,
      mentionBusinessName: true,
      apologiseForPoorExperiences: true,
      inviteUnhappyCustomersToContact: true,
      keepRepliesShortByDefault: false,
    },
  },
  {
    id: "example_plumbing_services_manchester",
    businessName: "Example Plumbing Services",
    businessType: "Trade",
    location: "Manchester",
    address: "Example Business Park, Manchester",
    googleRating: 4.9,
    googleReviewCount: 98,
    status: "Connected",
    brandVoice: {
      businessName: "Example Plumbing Services",
      businessType: "Trade",
      location: "Manchester",
      preferredTone: "Friendly",
      defaultLength: "Short",
      greetingStyle: "Use clear, practical wording",
      signOffStyle: "Thanks, the Example Plumbing Services team",
      wordsToUse: "on time, clear, tidy, fixed, helpful",
      wordsToAvoid: "fault, blame, guaranteed",
      complaintHandlingStyle:
        "Apologise for the experience, avoid arguing, and invite the customer to contact the team directly.",
      useEmojis: false,
      mentionBusinessName: true,
      apologiseForPoorExperiences: true,
      inviteUnhappyCustomersToContact: true,
      keepRepliesShortByDefault: true,
    },
  },
];

export const defaultBrandVoice: BrandVoiceSettings =
  demoLocations[0].brandVoice;

export const mockLocations: GoogleBusinessLocation[] = demoLocations.map(
  ({
    id,
    businessName,
    location,
    address,
    phone,
    website,
    googleRating,
    googleReviewCount,
    priceRange,
    status,
  }) => ({
    id,
    businessName,
    location,
    address,
    phone,
    website,
    googleRating,
    googleReviewCount,
    priceRange,
    status,
  }),
);

export const demoReviews: Review[] = [
  {
    id: "rev_example_hair_salon_sarah",
    customerName: "Sarah M",
    rating: 5,
    reviewText:
      "Brilliant service from start to finish. The team were friendly, professional, and I'm really pleased with the result. I'll definitely be coming back.",
    source: "Google",
    businessName: "Example Hair Salon",
    businessType: "Salon",
    location: "Leeds",
    address: "Example High Street, Leeds",
    googleRating: 4.8,
    googleReviewCount: 124,
    priceRange: "£20-50",
    dateReceived: "2026-06-09",
    status: "Draft ready",
    sentiment: "Positive",
    draftReplies: [
      "Hi Sarah, thank you for such a lovely review. We are delighted you were pleased with the result and that the team made you feel welcome from start to finish. Thanks, the Example Hair Salon team.",
      "Thank you, Sarah. It is brilliant to hear the service felt friendly and professional. We really appreciate your kind words and look forward to welcoming you back.",
      "Hi Sarah, thanks for taking the time to review Example Hair Salon. We are so pleased you were happy with the result and the service.",
    ],
  },
  {
    id: "rev_example_dental_practice_james",
    customerName: "James R",
    rating: 1,
    reviewText:
      "I waited nearly 45 minutes past my appointment time and no one explained the delay. It was frustrating and not the experience I expected.",
    source: "Google",
    businessName: "Example Dental Practice",
    businessType: "Dentist",
    location: "Manchester",
    address: "Example Road, Manchester",
    googleRating: 4.5,
    googleReviewCount: 89,
    dateReceived: "2026-06-08",
    status: "New",
    sentiment: "Complaint",
    draftReplies: [
      "Hi James, thank you for raising this. We are sorry to hear that your wait was longer than expected and that the delay was not explained clearly. Please contact Example Dental Practice directly so the team can look into this properly.",
      "Hello James, we appreciate you taking the time to share your experience. We understand how frustrating a delay can be, especially without an update. Please get in touch with the practice so this can be reviewed.",
      "Hi James, thank you for your feedback. We are disappointed to hear this was your experience and would like the opportunity to understand it in more detail. Please contact the practice directly at your convenience.",
    ],
  },
  {
    id: "rev_example_local_garage_imran",
    customerName: "Imran K",
    rating: 5,
    reviewText:
      "Quick MOT, fair price, and clear communication throughout. Really happy with the service.",
    source: "Google",
    businessName: "Example Local Garage",
    businessType: "Garage",
    location: "Bradford",
    address: "Example Industrial Estate, Bradford",
    googleRating: 4.7,
    googleReviewCount: 156,
    priceRange: "£50-150",
    dateReceived: "2026-06-07",
    status: "Posted",
    sentiment: "Positive",
    draftReplies: [
      "Thanks Imran, we really appreciate your review. It is great to hear you were happy with the MOT, pricing, and communication. Thanks, the Example Local Garage team.",
      "Hi Imran, thank you for choosing Example Local Garage. We are pleased the service was quick, fair, and clear throughout.",
      "Thank you, Imran. Clear communication and fair service are exactly what we aim for, so your feedback means a lot to the team.",
    ],
  },
  {
    id: "rev_example_indian_restaurant_priya",
    customerName: "Priya S",
    rating: 2,
    reviewText:
      "The food was nice, but the delivery was over an hour late and one item was missing from the order.",
    source: "Google",
    businessName: "Example Indian Restaurant",
    businessType: "Restaurant",
    location: "Birmingham",
    address: "Example Parade, Birmingham",
    googleRating: 4.4,
    googleReviewCount: 211,
    priceRange: "£10-20",
    dateReceived: "2026-06-06",
    status: "Edited",
    sentiment: "Complaint",
    draftReplies: [
      "Hi Priya, thank you for your feedback. We are pleased you enjoyed the food, but we are sorry the delivery was late and that an item was missing. Please contact Example Indian Restaurant directly with your order details so we can look into this for you.",
      "Hello Priya, thanks for letting us know. A late delivery and missing item is not the experience we want customers to have. Please get in touch with the restaurant so the team can review the order.",
      "Hi Priya, we appreciate your review and are glad the food was nice. We understand the delay and missing item were frustrating. Please contact us directly so we can follow this up.",
    ],
  },
  {
    id: "rev_example_estate_agents_rebecca",
    customerName: "Rebecca T",
    rating: 5,
    reviewText:
      "The team kept us updated throughout the process and made the sale feel much less stressful.",
    source: "Google",
    businessName: "Example Estate Agents",
    businessType: "Estate agent",
    location: "Leicester",
    address: "Example Market Street, Leicester",
    googleRating: 4.6,
    googleReviewCount: 73,
    dateReceived: "2026-06-05",
    status: "Copied",
    sentiment: "Positive",
    draftReplies: [
      "Thank you, Rebecca. We are pleased the team kept you updated and helped make the sale feel less stressful. Kind regards, the Example Estate Agents team.",
      "Hi Rebecca, thanks for your kind review. Clear updates throughout the process are really important to us, so it is great to hear this helped.",
      "Thank you for taking the time to review Example Estate Agents, Rebecca. We are glad the team supported you throughout the sale.",
    ],
  },
  {
    id: "rev_example_plumbing_services_mark",
    customerName: "Mark D",
    rating: 5,
    reviewText:
      "Arrived on time, explained the issue clearly, and fixed the leak without any fuss.",
    source: "Google",
    businessName: "Example Plumbing Services",
    businessType: "Trade",
    location: "Manchester",
    address: "Example Business Park, Manchester",
    googleRating: 4.9,
    googleReviewCount: 98,
    dateReceived: "2026-06-04",
    status: "Draft ready",
    sentiment: "Positive",
    draftReplies: [
      "Thanks Mark, we really appreciate your review. We are glad the leak was fixed clearly and without fuss. Thanks, the Example Plumbing Services team.",
      "Hi Mark, thank you for choosing Example Plumbing Services. Turning up on time and explaining the issue clearly is exactly what we aim for.",
      "Thank you, Mark. We are pleased we could help with the leak and appreciate you taking the time to leave a review.",
    ],
  },
];

export const savedReplies: SavedReply[] = demoReviews
  .filter((review) => review.status !== "New")
  .slice(0, 5)
  .map((review, index) => ({
    id: `saved_${review.id}`,
    reviewId: review.id,
    originalReviewSnippet: review.reviewText,
    replyPreview: review.draftReplies[0],
    tone: review.sentiment === "Complaint" ? "Empathetic" : "Friendly",
    businessType: review.businessType,
    dateSaved: `2026-06-0${9 - index}`,
    usageCount: [8, 6, 4, 7, 3][index],
    sentiment: review.sentiment,
  }));
